name: PR comment
# This workflow is triggered after the linting action is complete

on:
  workflow_run:
    workflows: ["En_GBLocalise in translations"]
    types: [completed]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      actions: write
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: on artifact
        id: artifact
        uses: marocchino/on_artifact@05d65253970dd4fe82aab699203380dbb65b3bca
        with:
          name: En_GBLocalise-logs

      - uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: En_GBLocalise-class ${{ steps.artifact.outputs.pr_number }}
          number: ${{ steps.artifact.outputs.pr_number }}
          message: |
           The following translation files contain the En_GBLocalise class on ${{ steps.artifact.outputs.pr_sha }}
            ```
            ${{ steps.artifact.outputs.en_gblocalise_result }}
            ```
            Affecting ${{ steps.artifact.outputs.files_affected }} files in ${{ steps.artifact.outputs.languagepacks_affected }} language packs.

